# -*- coding: utf-8 -*-
"""Assignmnet_7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-cGdhRhEVZq15LyvbFl7vncZIMP487WL
"""

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

iris =load_iris()
x=iris.data
y=iris.target
feature_names=iris.feature_names
target_names=iris.target_names

print("Feature Names",feature_names)
print("Target Names",target_names)

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

print("total samples",len(x))
print("train saples",len(x_train))
print("test samples",len(x_test))

model = GaussianNB()
model.fit(x_train,y_train)

y_pred=model.predict(x_test)

accuracy=accuracy_score(y_test,y_pred)

print("y test dataset",y_test)
print("y pred dataset",y_pred)
print("Accuracy Score",accuracy*100)